<a href="https://colab.research.google.com/github/shreshthasharma110/PANDAS_LEARNING/blob/main/01_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

Creating a series in list

In [3]:
s = pd.Series([100,200,300,400,500,])
s

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [4]:
s.dtype

dtype('int64')

In [5]:
s.values

array([100, 200, 300, 400, 500])

In [6]:
s.index # to check index

RangeIndex(start=0, stop=5, step=1)

Assigning name to a column

In [15]:
s.name = 'calories'
s

0    100
1    200
2    300
3    400
4    500
Name: calories, dtype: int64

Indexing

In [8]:
s[0]

np.int64(100)

In [9]:
s[0:3] # start(included) : stop(excluded) : step value(values to jump)

0    100
1    200
2    300
Name: Numbers, dtype: int64

In [13]:
s[0:5:2] # 2 is the step value

0    100
2    300
4    500
Name: Numbers, dtype: int64

In [14]:
# iloc -> location based indexing

s.iloc[3]

np.int64(400)

In [16]:
index = ["apple",'banana','grapes','oranges','pineapple']

In [18]:
s.index =index
s

apple        100
banana       200
grapes       300
oranges      400
pineapple    500
Name: calories, dtype: int64

In [20]:
#loc -> label based indexing
s.loc['oranges']

np.int64(400)

In [21]:
# In label based indexing your start as well as stop value both are included in the output

Creating a series using dictionary

In [24]:
fruit_protien ={
    'Avocado': 2.0 ,  # protien in grams
    'Apple':5.0,
    'Blackberries':1.1,
    'Kiwi':7.0,
    'Mango':3.3,
    'Cherries':4.2
}

In [30]:
s2 = pd.Series(fruit_protien , name = 'protien in gm')
s2

Avocado         2.0
Apple           5.0
Blackberries    1.1
Kiwi            7.0
Mango           3.3
Cherries        4.2
Name: protien in gm, dtype: float64