<a href="https://colab.research.google.com/github/shreshthasharma110/PANDAS_LEARNING/blob/main/02_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATAFRAME

In [47]:
import pandas as pd
import numpy as np

In [48]:
data = {'Name':['Alice','bob','charlie','david','Eve'],
        'Age':[25,30,np.nan,28,35],
        'Department':['HR','IT','Finance','IT',"HR"],
        'Salary':[50000,60000,70000,np.nan,50000],
        }

In [49]:
data

{'Name': ['Alice', 'bob', 'charlie', 'david', 'Eve'],
 'Age': [25, 30, nan, 28, 35],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
 'Salary': [50000, 60000, 70000, nan, 50000]}

In [50]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      bob  30.0         IT  60000.0
2  charlie   NaN    Finance  70000.0
3    david  28.0         IT      NaN
4      Eve  35.0         HR  50000.0

In [51]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    bob  30.0         IT  60000.0

In [52]:
df.tail(2)

    Name   Age Department   Salary
3  david  28.0         IT      NaN
4    Eve  35.0         HR  50000.0

In [53]:
# loc and iloc function to fetch
# iloc for position based indexing
# loc for label based indexing

df.iloc[1:3]

      Name   Age Department   Salary
1      bob  30.0         IT  60000.0
2  charlie   NaN    Finance  70000.0

In [54]:
df.loc[1:3 ,['Age','Department']]

    Age Department
1  30.0         IT
2   NaN    Finance
3  28.0         IT

In [55]:
df[['Age','Department']]

    Age Department
0  25.0         HR
1  30.0         IT
2   NaN    Finance
3  28.0         IT
4  35.0         HR

In [56]:
df.drop('Age', axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      bob         IT  60000.0
2  charlie    Finance  70000.0
3    david         IT      NaN
4      Eve         HR  50000.0

In [57]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      bob  30.0         IT  60000.0
2  charlie   NaN    Finance  70000.0
3    david  28.0         IT      NaN
4      Eve  35.0         HR  50000.0

In [58]:
# tell the shape of the dataset

df.shape

(5, 4)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Department  5 non-null      object
 3   Salary      4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [61]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   29.500000  57500.000000
std     4.203173   9574.271078
min    25.000000  50000.000000
25%    27.250000  50000.000000
50%    29.000000  55000.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

In [62]:
# Broadcasting = expanding smaller values to perform operations on larger DataFrame

df['Salary'] = df['Salary'] +5000
df['Salary']

0    55000.0
1    65000.0
2    75000.0
3        NaN
4    55000.0
Name: Salary, dtype: float64

In [69]:
# rename columns :

df.rename(columns = {"Department" : "Dept"}, inplace = True)

In [73]:
df['Salary'].unique()

array([55000., 65000., 75000.,    nan])

In [74]:
df['Dept'].value_counts()

Dept
HR         2
IT         2
Finance    1
Name: count, dtype: int64

In [75]:
df['Promoted Salary'] = df['Salary'] *10
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      bob  30.0       IT  65000.0         650000.0
2  charlie   NaN  Finance  75000.0         750000.0
3    david  28.0       IT      NaN              NaN
4      Eve  35.0       HR  55000.0         550000.0