<a href="https://colab.research.google.com/github/shreshthasharma110/PANDAS_LEARNING/blob/main/03_data_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

creating a sample dataset[link text](https://)

In [7]:
employee_data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [24, 29, 31, 26, 28],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 55000, 62000, 51000, 47000]
}

df = pd.DataFrame(employee_data)
df

    ID     Name  Age Department  Salary
0  101    Alice   24         HR   40000
1  102      Bob   29         IT   55000
2  103  Charlie   31    Finance   62000
3  104    David   26         IT   51000
4  105     Emma   28  Marketing   47000

In [8]:
df.to_csv('employee_data.csv' , index = False)

reading dataset

In [9]:
data = pd.read_csv('employee_data.csv')
data

    ID     Name  Age Department  Salary
0  101    Alice   24         HR   40000
1  102      Bob   29         IT   55000
2  103  Charlie   31    Finance   62000
3  104    David   26         IT   51000
4  105     Emma   28  Marketing   47000

In [11]:
data.head(3)

    ID     Name  Age Department  Salary
0  101    Alice   24         HR   40000
1  102      Bob   29         IT   55000
2  103  Charlie   31    Finance   62000

In [12]:
data.tail(3)

    ID     Name  Age Department  Salary
2  103  Charlie   31    Finance   62000
3  104    David   26         IT   51000
4  105     Emma   28  Marketing   47000

In [13]:
data.shape

(5, 5)

columns names

In [15]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [17]:
data['Salary']

0    40000
1    55000
2    62000
3    51000
4    47000
Name: Salary, dtype: int64

data types

In [19]:
data.dtypes

ID             int64
Name          object
Age            int64
Department    object
Salary         int64
dtype: object

dataset information

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          5 non-null      int64
 1   Name        5 non-null      object
 2   Age         5 non-null      int64
 3   Department  5 non-null      object
 4   Salary      5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

Statistical Summary

In [22]:
data.describe()

               ID        Age        Salary
count    5.000000   5.000000      5.000000
mean   103.000000  27.600000  51000.000000
std      1.581139   2.701851   8276.472679
min    101.000000  24.000000  40000.000000
25%    102.000000  26.000000  47000.000000
50%    103.000000  28.000000  51000.000000
75%    104.000000  29.000000  55000.000000
max    105.000000  31.000000  62000.000000

now inclduing text columns

In [23]:
data.describe(include = 'all')

                ID   Name        Age Department        Salary
count     5.000000      5   5.000000          5      5.000000
unique         NaN      5        NaN          4           NaN
top            NaN  Alice        NaN         IT           NaN
freq           NaN      1        NaN          2           NaN
mean    103.000000    NaN  27.600000        NaN  51000.000000
std       1.581139    NaN   2.701851        NaN   8276.472679
min     101.000000    NaN  24.000000        NaN  40000.000000
25%     102.000000    NaN  26.000000        NaN  47000.000000
50%     103.000000    NaN  28.000000        NaN  51000.000000
75%     104.000000    NaN  29.000000        NaN  55000.000000
max     105.000000    NaN  31.000000        NaN  62000.000000