<a href="https://colab.research.google.com/github/shreshthasharma110/PANDAS_LEARNING/blob/main/04_data_cleanong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Alice"],
    "Age": [24, None, 31, 26, 24],
    "Department": ["HR", "IT", None, "IT", "HR"],
    "Salary": [40000, 55000, 62000, None, 40000]
}

df = pd.DataFrame(data)

df

      Name   Age Department   Salary
0    Alice  24.0         HR  40000.0
1      Bob   NaN         IT  55000.0
2  Charlie  31.0       None  62000.0
3    David  26.0         IT      NaN
4    Alice  24.0         HR  40000.0

check missing values

In [3]:
df.isnull()

    Name    Age  Department  Salary
0  False  False       False   False
1  False   True       False   False
2  False  False        True   False
3  False  False       False    True
4  False  False       False   False

count missing values

In [5]:
df.isnull().sum()

Name          0
Age           1
Department    1
Salary        1
dtype: int64

removing missing value

In [6]:
df.dropna()

    Name   Age Department   Salary
0  Alice  24.0         HR  40000.0
4  Alice  24.0         HR  40000.0

In [7]:
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David
4    Alice